version: '3.7'
services:
  web:
    image: nginx
    container_name: walle-nginx
    hostname: nginx-web
    ports:
      - "80:80"
    volumes:
      - ./fe/:/opt/walle-web/:ro
      - ./gateway/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - python
    depends_on:
      - python
    networks:
      - walle-net
    restart: always

  python:
    image: alenx/walle-web
    container_name: walle-python
    hostname: walle-python
    volumes:
      - $PWD/:/opt/walle-web/
    command: >
      bash -c "sed -i \n 's/user/walle/g;s/password/walle/g;s/localhost/db/g' /opt/walle-web/walle/config/settings_prod.py
      && python /opt/walle-web/waller.py"
    expose:
      - "5000"
    links:
      - db
    depends_on:
      - db
    networks:
      - walle-net
    restart: always

  db:
    image: mysql
    container_name: walle-mysql
    hostname: walle-mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: walle
      MYSQL_DATABASE: walle
    volumes:
      - /tmp/mysql:/var/lib/mysql
#      - /data/walle/mysql:/var/lib/mysql
    networks:
      - walle-net
    restart: always

  adminer:
    image: adminer
    container_name: walle-adminer
    links:
      - db
    ports:
      - "8888:8080"
    networks:
      - walle-net
    restart: always

networks:
  walle-net:
    driver: bridge